[package]
name = "rust-evm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = { version = "0.11.1", default-features = true, features = ["rlp"] }
sha3 = "0.8"
rlp = "0.5.1"